# -*- coding: utf-8 -*-
"""wine_classification_cap2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVFZdZ3UxxQHYI6cPCZwZpidtcS-wSb3

# Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import pandas as pd
import os
import time
import warnings
warnings.filterwarnings('ignore')

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "wine_classification"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

np.random.seed(42)
print('✅ Setup concluído!')
print(f'   Python       : {sys.version.split()[0]}')
print(f'   Scikit-Learn : {sklearn.__version__}')

"""# Get the Data

## Download the Data
"""

from sklearn.datasets import load_wine

def fetch_wine_data():
    """Carrega o Wine Recognition Dataset do sklearn.
    Equivalente ao fetch_housing_data() do Cap. 2 original.
    Fonte: UCI ML Repository / Kaggle: harrywang/wine-dataset-for-clustering
    """
    raw = load_wine()
    df  = pd.DataFrame(raw.data, columns=raw.feature_names)
    df['target'] = raw.target  # 0=Cultivar A | 1=Cultivar B | 2=Cultivar C
    return df, raw.target_names

wine, TARGET_NAMES = fetch_wine_data()
print('✅ Dataset carregado!')
print(f'   Fonte   : UCI Machine Learning Repository / Kaggle')
print(f'   Shape   : {wine.shape}')
print(f'   Classes : {list(TARGET_NAMES)}')

"""## Take a Quick Look at the Data Structure"""

wine.head()

wine.info()

wine['target'].value_counts()

wine.describe()

# Histogramas de todas as features
wine.hist(bins=30, figsize=(22, 16))
save_fig("attribute_histogram_plots")
plt.show()

"""## Create a Test Set"""

# StratifiedShuffleSplit
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in split.split(wine, wine["target"]):
    strat_train_set = wine.loc[train_index].reset_index(drop=True)
    strat_test_set  = wine.loc[test_index].reset_index(drop=True)

print(f'Treino : {len(strat_train_set):,} amostras')
print(f'Teste  : {len(strat_test_set):,} amostras')
print()
print('Proporção das classes:')
print('  Dataset completo:')
print(wine['target'].value_counts() / len(wine))
print('  Treino:')
print(strat_train_set['target'].value_counts() / len(strat_train_set))

# Verificar proporção preservada
def target_proportions(data):
    return data['target'].value_counts() / len(data)

compare_props = pd.DataFrame({
    'Geral':       target_proportions(wine),
    'Treino':      target_proportions(strat_train_set),
    'Teste':       target_proportions(strat_test_set),
})
compare_props['Erro % (Treino)'] = (
    100 * compare_props['Treino'] / compare_props['Geral'] - 100
).round(2)
compare_props

"""# Discover and Visualize the Data to Gain Insights"""

wine_train = strat_train_set.copy()

"""## Visualizing the Data"""

# Distribuição do target
CORES_CLS = ['#8e44ad','#e67e22','#16a085']

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

counts = wine_train['target'].value_counts().sort_index()
rotulos = ['Cultivar A (0)','Cultivar B (1)','Cultivar C (2)']

bars = ax1.bar(rotulos, counts.values, color=CORES_CLS, edgecolor='white', width=0.5)
for b in bars:
    ax1.text(b.get_x()+b.get_width()/2, b.get_height()+0.3,
             f'{int(b.get_height())} ({b.get_height()/len(wine_train)*100:.1f}%)',
             ha='center', fontweight='bold')
ax1.set_title('Distribuição das Classes (Treino)', fontweight='bold')
ax1.set_ylabel('Amostras')
ax1.set_ylim(0, max(counts.values)*1.2)

ax2.pie(counts.values, labels=['Cultivar A','Cultivar B','Cultivar C'],
        colors=CORES_CLS, autopct='%1.1f%%', startangle=90,
        wedgeprops=dict(edgecolor='white', linewidth=2))
ax2.set_title('Proporção das Classes', fontweight='bold')

save_fig("target_distribution")
plt.show()

# Boxplots das features mais discriminativas
from sklearn.feature_selection import f_classif

X_vis = wine_train.drop('target', axis=1)
y_vis = wine_train['target']
f_scores, _ = f_classif(X_vis, y_vis)
top8_idx  = np.argsort(f_scores)[::-1][:8]
top8_feat = [X_vis.columns[i] for i in top8_idx]

wine_plot = wine_train.copy()
wine_plot['Cultivar'] = wine_plot['target'].map(
    {0:'Cultivar A', 1:'Cultivar B', 2:'Cultivar C'})

fig, axes = plt.subplots(2, 4, figsize=(20, 9))
axes = axes.flatten()
pal = {'Cultivar A': CORES_CLS[0], 'Cultivar B': CORES_CLS[1], 'Cultivar C': CORES_CLS[2]}

for i, feat in enumerate(top8_feat):
    sns.boxplot(data=wine_plot, x='Cultivar', y=feat,
                palette=pal, ax=axes[i], width=0.45, linewidth=1.5)
    axes[i].set_title(feat.replace('_',' ').title(), fontweight='bold', fontsize=10)
    axes[i].set_xlabel('')

plt.suptitle('Top 8 Features Mais Discriminativas (F-score ANOVA)',
             fontsize=14, fontweight='bold')
save_fig("best_features_boxplots")
plt.show()

"""## Looking for Correlations"""

corr_matrix = wine_train.corr(numeric_only=True)
corr_matrix['target'].sort_values(ascending=False)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 7))

mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f',
            cmap='RdYlGn', linewidths=0.3, ax=ax1,
            vmin=-1, vmax=1, annot_kws={'size': 8})
ax1.set_title('Mapa de Correlação — Wine Dataset', fontweight='bold')

tc = corr_matrix['target'].drop('target').abs().sort_values(ascending=False)
cores_bar = ['#e74c3c' if corr_matrix['target'][f]<0 else '#3498db' for f in tc.index]
tc.plot(kind='barh', ax=ax2, color=cores_bar[::-1], edgecolor='white')
ax2.invert_yaxis()
ax2.set_title('|Correlação| com Target (Cultivar)', fontweight='bold')
ax2.set_xlabel('|Correlação de Pearson|')
for i, v in enumerate(tc.values):
    ax2.text(v+0.005, i, f'{v:.3f}', va='center', fontsize=9)

save_fig("correlation_matrix")
plt.show()

# Scatter matrix
from pandas.plotting import scatter_matrix

top4 = top8_feat[:4]
scatter_matrix(wine_train[top4], figsize=(12, 8))
save_fig("scatter_matrix")
plt.show()

"""## Experimenting with Attribute Combinations"""

# Criar features combinadas
wine_train['alcohol_acid_ratio']  = wine_train['alcohol'] / (wine_train['malic_acid'] + 1e-6)
wine_train['polyphenol_index']    = wine_train['total_phenols'] + wine_train['flavanoids'] + wine_train['proanthocyanins']
wine_train['flavanoid_ratio']     = wine_train['flavanoids'] / (wine_train['total_phenols'] + 1e-6)
wine_train['color_score']         = wine_train['color_intensity'] * wine_train['hue']

# Verificar correlação das novas features
corr_matrix2 = wine_train.corr(numeric_only=True)
novas = ['alcohol_acid_ratio','polyphenol_index','flavanoid_ratio','color_score']
print('Correlação das novas features com target:')
print(corr_matrix2['target'][novas].sort_values(ascending=False).round(3))

"""# Prepare the Data for Machine Learning Algorithms"""

# Separar features e target
wine_feat = strat_train_set.drop('target', axis=1)
wine_labels = strat_train_set['target'].copy()

print(f'X_train shape: {wine_feat.shape}')
print(f'y_train shape: {wine_labels.shape}')

"""## Data Cleaning"""

# Verificar valores ausentes
print('Valores ausentes por coluna:')
missing = wine_feat.isnull().sum()
if missing.sum() == 0:
    print('  ✅ Nenhum valor ausente! (Wine dataset já vem limpo)')
else:
    print(missing[missing > 0])

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
wine_num = wine_feat.select_dtypes(include=[np.number])
imputer.fit(wine_num)
print()
print('Medianas calculadas pelo imputer:')
print(pd.Series(imputer.statistics_, index=wine_num.columns).round(3))

"""## Custom Transformers"""

# Transformer customizado
from sklearn.base import BaseEstimator, TransformerMixin

class WineAttributesAdder(BaseEstimator, TransformerMixin):
    """
    Equivalente ao CombinedAttributesAdder do Cap. 2.
    Cria features derivadas com significado químico/enológico.
    """
    def __init__(self, add_color_score=True):
        self.add_color_score = add_color_score

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        # Razão álcool / acidez — equilíbrio sensorial
        X['alcohol_acid_ratio'] = X['alcohol'] / (X['malic_acid'] + 1e-6)
        # Índice de polifenóis — qualidade antioxidante
        X['polyphenol_index']   = X['total_phenols'] + X['flavanoids'] + X['proanthocyanins']
        # Razão flavonoides / fenóis totais — indicador de maturidade
        X['flavanoid_ratio']    = X['flavanoids'] / (X['total_phenols'] + 1e-6)
        if self.add_color_score:
            # Score de cor — intensidade × tonalidade
            X['color_score']    = X['color_intensity'] * X['hue']
        return X

# Testar
adder = WineAttributesAdder()
X_extra = adder.fit_transform(wine_feat)
novas = set(X_extra.columns) - set(wine_feat.columns)
print(f'Features originais : {wine_feat.shape[1]}')
print(f'Após transformer   : {X_extra.shape[1]}')
print(f'Novas features     : {sorted(novas)}')

"""## Transformation Pipelines"""

# Pipeline numérico
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
    ('attribs_adder', WineAttributesAdder()),
    ('imputer',       SimpleImputer(strategy='median')),
    ('std_scaler',    StandardScaler()),
])

wine_num_tr = num_pipeline.fit_transform(wine_feat)
print(f'Shape após pipeline numérico: {wine_num_tr.shape}')
print(f'  ({wine_feat.shape[1]} originais + 4 novas = {wine_num_tr.shape[1]} features)')

# Pipeline completo (wine não tem categóricas — pipeline direto)
full_pipeline = num_pipeline

wine_prepared = full_pipeline.fit_transform(wine_feat)
print(f'wine_prepared shape: {wine_prepared.shape}')
print('✅ Pipeline de pré-processamento pronto!')

"""# Select and Train a Model

## Training and Evaluating on the Training Set
"""

# ── KNN ──────────────────────────────────────────────────────────────────────
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

knn_reg = KNeighborsClassifier(n_neighbors=5)
knn_reg.fit(wine_prepared, wine_labels)

some_data     = wine_feat.iloc[:5]
some_labels   = wine_labels.iloc[:5]
some_prepared = full_pipeline.transform(some_data)

print('KNN — Predições (5 primeiras instâncias):')
print('  Predições:', knn_reg.predict(some_prepared))
print('  Rótulos  :', list(some_labels))

from sklearn.metrics import mean_squared_error

wine_predictions = knn_reg.predict(wine_prepared)
knn_acc = accuracy_score(wine_labels, wine_predictions)
knn_f1  = f1_score(wine_labels, wine_predictions, average='macro')
print(f'KNN — Acurácia  (treino): {knn_acc:.4f}')
print(f'KNN — F1-Macro  (treino): {knn_f1:.4f}')

# ── Random Forest ─────────────────────────────────────────────────────────────
from sklearn.ensemble import RandomForestClassifier

forest_reg = RandomForestClassifier(n_estimators=100, random_state=42)
forest_reg.fit(wine_prepared, wine_labels)

wine_predictions_rf = forest_reg.predict(wine_prepared)
rf_acc = accuracy_score(wine_labels, wine_predictions_rf)
rf_f1  = f1_score(wine_labels, wine_predictions_rf, average='macro')
print(f'Random Forest — Acurácia (treino): {rf_acc:.4f}')
print(f'Random Forest — F1-Macro (treino): {rf_f1:.4f}')

# ── Naive Bayes ───────────────────────────────────────────────────────────────
from sklearn.naive_bayes import GaussianNB

nb_reg = GaussianNB()
nb_reg.fit(wine_prepared, wine_labels)

wine_predictions_nb = nb_reg.predict(wine_prepared)
nb_acc = accuracy_score(wine_labels, wine_predictions_nb)
nb_f1  = f1_score(wine_labels, wine_predictions_nb, average='macro')
print(f'Naive Bayes — Acurácia (treino): {nb_acc:.4f}')
print(f'Naive Bayes — F1-Macro (treino): {nb_f1:.4f}')

"""## Better Evaluation Using Cross-Validation"""

#cross_val_score com 10 folds
from sklearn.model_selection import cross_val_score

def display_scores(scores, label='Score'):
    print(f'{label}:')
    print(f'  Scores : {scores.round(4)}')
    print(f'  Média  : {scores.mean():.4f}')
    print(f'  Desvio : {scores.std():.4f}')

# KNN — Cross-Validation
knn_scores = cross_val_score(knn_reg, wine_prepared, wine_labels,
                              scoring='roc_auc_ovr', cv=10)
display_scores(knn_scores, 'KNN — AUC-ROC OvR (10-fold CV)')

# Random Forest — Cross-Validation
forest_scores = cross_val_score(forest_reg, wine_prepared, wine_labels,
                                 scoring='roc_auc_ovr', cv=10)
display_scores(forest_scores, 'Random Forest — AUC-ROC OvR (10-fold CV)')

# Naive Bayes — Cross-Validation
nb_scores = cross_val_score(nb_reg, wine_prepared, wine_labels,
                             scoring='roc_auc_ovr', cv=10)
display_scores(nb_scores, 'Naive Bayes — AUC-ROC OvR (10-fold CV)')

# Comparação gráfica — AUC CV 10-fold
from sklearn.model_selection import StratifiedKFold, cross_validate

cv5 = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
SCORING = ['accuracy','roc_auc_ovr','f1_macro','precision_macro','recall_macro']
CORES_ALG = ['#e74c3c','#27ae60','#3498db']
NOMES_ALG = ['KNN','Random Forest','Naive Bayes']

cv_results = {}
for nome, modelo in zip(NOMES_ALG, [knn_reg, forest_reg, nb_reg]):
    res = cross_validate(modelo, wine_prepared, wine_labels,
                         cv=cv5, scoring=SCORING, return_train_score=True)
    cv_results[nome] = {m: {'mean': res[f'test_{m}'].mean(),
                             'std':  res[f'test_{m}'].std(),
                             'folds': res[f'test_{m}']}
                        for m in SCORING}
    print(f"{nome:20s} AUC={cv_results[nome]['roc_auc_ovr']['mean']:.4f}±{cv_results[nome]['roc_auc_ovr']['std']:.4f}"
          f" | F1={cv_results[nome]['f1_macro']['mean']:.4f}"
          f" | ACC={cv_results[nome]['accuracy']['mean']:.4f}")

# Tabela Média ± Desvio — todas as métricas
NOMES_MET = {'accuracy':'Acurácia','roc_auc_ovr':'AUC-ROC (OvR)',
             'f1_macro':'F1-Macro','precision_macro':'Precisão','recall_macro':'Recall'}

rows = []
for nome in NOMES_ALG:
    row = {'Algoritmo': nome}
    for m, lbl in NOMES_MET.items():
        row[lbl] = f"{cv_results[nome][m]['mean']:.4f} ± {cv_results[nome][m]['std']:.4f}"
    rows.append(row)

df_cv = pd.DataFrame(rows).set_index('Algoritmo')
print('📊 Cross-Validation (5-fold) — Média ± Desvio Padrão:')
df_cv

# Gráfico comparativo de métricas — 5 painéis
metricas_plot = ['accuracy','roc_auc_ovr','f1_macro','precision_macro','recall_macro']
nomes_plot    = ['Acurácia','AUC-ROC (OvR)','F1-Macro','Precisão','Recall']

fig, axes = plt.subplots(1, 5, figsize=(24, 6))
for ax, met, lbl in zip(axes, metricas_plot, nomes_plot):
    means = [cv_results[n][met]['mean'] for n in NOMES_ALG]
    stds  = [cv_results[n][met]['std']  for n in NOMES_ALG]
    best  = int(np.argmax(means))
    bars = ax.bar(range(3), means, color=CORES_ALG, edgecolor='white', alpha=0.88, width=0.55)
    ax.errorbar(range(3), means, yerr=stds, fmt='none', color='#2c3e50', capsize=6, lw=2)
    bars[best].set_edgecolor('#2c3e50'); bars[best].set_linewidth(2.8)
    ax.text(best, means[best]+stds[best]+0.01,'🏆', ha='center', fontsize=14)
    ax.set_title(lbl, fontweight='bold', fontsize=12)
    ax.set_xticks(range(3)); ax.set_xticklabels(NOMES_ALG, fontsize=10)
    ax.set_ylim(0.85, 1.06)
    for b, m in zip(bars, means):
        ax.text(b.get_x()+b.get_width()/2, b.get_height()-0.018, f'{m:.4f}',
                ha='center', va='top', color='white', fontweight='bold', fontsize=10)

plt.suptitle('Comparação de Desempenho — Cross-Validation 5-Fold\nWine Dataset — KNN · Random Forest · Naive Bayes',
             fontsize=14, fontweight='bold', y=1.02)
save_fig("cv_comparison")
plt.show()

# Radar Chart — perfil completo de cada algoritmo
cats   = ['Acurácia','AUC-ROC','F1-Macro','Precisão','Recall']
met_k  = ['accuracy','roc_auc_ovr','f1_macro','precision_macro','recall_macro']
N      = len(cats)
angles = [n/float(N)*2*np.pi for n in range(N)] + [0]

fig, axes = plt.subplots(1, 3, figsize=(18, 6), subplot_kw=dict(polar=True))
for ax, nome, cor in zip(axes, NOMES_ALG, CORES_ALG):
    vals = [cv_results[nome][m]['mean'] for m in met_k] + [cv_results[nome][met_k[0]]['mean']]
    ax.plot(angles, vals, 'o-', lw=2.5, color=cor)
    ax.fill(angles, vals, alpha=0.25, color=cor)
    ax.set_xticks(angles[:-1]); ax.set_xticklabels(cats, fontsize=11)
    ax.set_ylim(0.85, 1.0)
    ax.set_title(nome, fontsize=13, fontweight='bold', pad=20, color=cor)
    for angle, val in zip(angles[:-1], vals[:-1]):
        ax.text(angle, val+0.012, f'{val:.3f}', ha='center', fontsize=9, color=cor, fontweight='bold')

plt.suptitle('Radar Chart — Perfil Completo por Algoritmo', fontsize=14, fontweight='bold', y=1.02)
save_fig("radar_chart")
plt.show()

"""# Fine-Tune Your Model

## Grid Search
"""

#GridSearchCV no melhor modelo (Random Forest)
from sklearn.model_selection import GridSearchCV

param_grid = [
    # Grade 1: 3×2 = 6 combinações
    {'n_estimators': [50, 100, 200], 'max_features': ['sqrt', 'log2']},
    # Grade 2: 3×2 = 6 combinações com profundidade limitada
    {'n_estimators': [50, 100], 'max_features': ['sqrt', 'log2'], 'max_depth': [5, 10]},
]

forest_reg2  = RandomForestClassifier(random_state=42)
grid_search  = GridSearchCV(
    forest_reg2, param_grid,
    cv=5, scoring='roc_auc_ovr',
    verbose=1, n_jobs=-1
)
grid_search.fit(wine_prepared, wine_labels)

# Melhores hiperparâmetros
grid_search.best_params_

grid_search.best_estimator_

# Score de cada combinação testada
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres['mean_test_score'], cvres['params']):
    print(round(mean_score, 4), params)

pd.DataFrame(grid_search.cv_results_)[[
    'params','mean_test_score','std_test_score','rank_test_score'
]].sort_values('rank_test_score').head(10)

"""## Randomized Search"""

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs = {
    'n_neighbors': randint(low=3, high=15),
    'weights':     ['uniform', 'distance'],
    'metric':      ['euclidean', 'manhattan', 'minkowski'],
}

knn_reg2   = KNeighborsClassifier()
rnd_search = RandomizedSearchCV(
    knn_reg2, param_distribs,
    n_iter=20, cv=5,
    scoring='roc_auc_ovr',
    random_state=42, verbose=1, n_jobs=-1
)
rnd_search.fit(wine_prepared, wine_labels)

cvres = rnd_search.cv_results_
for mean_score, params in zip(cvres['mean_test_score'], cvres['params']):
    print(round(mean_score, 4), params)

"""## Analyze the Best Models and Their Errors"""

# Importância das features
feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances

# Nomes das features após o pipeline
feat_names_orig = list(wine_feat.columns)
feat_names_new  = feat_names_orig + ['alcohol_acid_ratio','polyphenol_index','flavanoid_ratio','color_score']

fi_df = pd.DataFrame({'Feature': feat_names_new, 'Importance': feature_importances})\
          .sort_values('Importance', ascending=False)

sorted(zip(feature_importances, feat_names_new), reverse=True)

# Gráfico de importância das features
novas_set = {'alcohol_acid_ratio','polyphenol_index','flavanoid_ratio','color_score'}
bar_colors = ['#e67e22' if f in novas_set else '#3498db' for f in fi_df['Feature']]

fig, ax = plt.subplots(figsize=(10, 8))
ax.barh(fi_df['Feature'][::-1], fi_df['Importance'][::-1],
        color=bar_colors[::-1], edgecolor='white')
ax.set_title('Importância das Features — Random Forest (Grid Search)', fontweight='bold')
ax.set_xlabel('Importância (Gini)')
from matplotlib.patches import Patch
ax.legend(handles=[Patch(facecolor='#e67e22', label='Feature nova (WineAttributesAdder)'),
                   Patch(facecolor='#3498db', label='Feature original')],
          loc='lower right', fontsize=9)
save_fig("feature_importances")
plt.show()

"""## Evaluate Your System on the Test Set"""

from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
from sklearn.preprocessing import label_binarize

final_model = grid_search.best_estimator_

X_test       = strat_test_set.drop('target', axis=1)
y_test       = strat_test_set['target'].copy()
X_test_prep  = full_pipeline.transform(X_test)

final_preds  = final_model.predict(X_test_prep)
final_probas = final_model.predict_proba(X_test_prep)

final_auc = roc_auc_score(y_test, final_probas, multi_class='ovr')
final_f1  = f1_score(y_test, final_preds, average='macro')
final_acc = accuracy_score(y_test, final_preds)

print('📊 RESULTADO FINAL NO CONJUNTO DE TESTE')
print('='*50)
print(f'Modelo  : Random Forest (Grid Search)')
print(f'Params  : {grid_search.best_params_}')
print()
print(f'AUC-ROC (OvR) : {final_auc:.4f}')
print(f'F1-Macro      : {final_f1:.4f}')
print(f'Acurácia      : {final_acc:.4f}')
print()
print(classification_report(y_test, final_preds,
                             target_names=['Cultivar A','Cultivar B','Cultivar C']))

# Matrizes de confusão
modelos_finais = {
    'KNN':                knn_reg,
    'Random Forest':      forest_reg,
    'Naive Bayes':        nb_reg,
    'RF (Grid Search)':   grid_search.best_estimator_,
    'KNN (Rnd Search)':   rnd_search.best_estimator_,
}

fig, axes = plt.subplots(1, 5, figsize=(26, 5))
for ax, (nome, modelo) in zip(axes, modelos_finais.items()):
    yp  = modelo.predict(X_test_prep)
    ypr = modelo.predict_proba(X_test_prep)
    cm  = confusion_matrix(y_test, yp)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['A','B','C'], yticklabels=['A','B','C'],
                linewidths=0.8, linecolor='white', annot_kws={'size':13,'weight':'bold'})
    auc_v = roc_auc_score(y_test, ypr, multi_class='ovr')
    f1_v  = f1_score(y_test, yp, average='macro')
    ax.set_title(f'{nome}\nAUC={auc_v:.3f} | F1={f1_v:.3f}', fontweight='bold', fontsize=10)
    ax.set_xlabel('Predito'); ax.set_ylabel('Real')

plt.suptitle('Matrizes de Confusão — Conjunto de Teste', fontsize=13, fontweight='bold')
save_fig("confusion_matrices")
plt.tight_layout()
plt.show()

# Curvas ROC One-vs-Rest
CORES_WINE = ['#8e44ad','#e67e22','#16a085']
y_test_bin = label_binarize(y_test, classes=[0,1,2])

fig, axes = plt.subplots(1, 3, figsize=(20, 6))
for ax, (nome, modelo), cor_alg in zip(axes,
    list(modelos_finais.items())[:3], ['#e74c3c','#27ae60','#3498db']):
    ypr = modelo.predict_proba(X_test_prep)
    for cls_i, (cor_c, lbl_c) in enumerate(zip(CORES_WINE,['Cultivar A','Cultivar B','Cultivar C'])):
        fpr, tpr, _ = roc_curve(y_test_bin[:, cls_i], ypr[:, cls_i])
        ax.plot(fpr, tpr, lw=2, color=cor_c, label=f'{lbl_c} (AUC={auc(fpr,tpr):.3f})')
    ax.plot([0,1],[0,1],':',color='gray',lw=1.5)
    ax.set_xlabel('FPR'); ax.set_ylabel('TPR')
    ax.set_title(f'Curvas ROC — {nome}\n(One-vs-Rest)', fontweight='bold', fontsize=11)
    ax.legend(loc='lower right', fontsize=9)

plt.suptitle('Curvas ROC OvR — KNN · Random Forest · Naive Bayes',
             fontsize=13, fontweight='bold')
save_fig("roc_curves")
plt.tight_layout()
plt.show()

from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, roc_curve, auc,
    confusion_matrix, classification_report
)
from sklearn.preprocessing import label_binarize

# Ranking final
rank_rows = []
for nome, modelo in modelos_finais.items():
    yp  = modelo.predict(X_test_prep)
    ypr = modelo.predict_proba(X_test_prep)
    rank_rows.append({
        'Modelo':      nome,
        'AUC-ROC(OvR)': roc_auc_score(y_test, ypr, multi_class='ovr'),
        'F1-Macro':    f1_score(y_test, yp, average='macro'),
        'Acurácia':    accuracy_score(y_test, yp),
        'Precisão':    precision_score(y_test, yp, average='macro'),
        'Recall':      recall_score(y_test, yp, average='macro'),
        'Erros':       int((yp != y_test.values).sum()),
    })

df_rank = pd.DataFrame(rank_rows).set_index('Modelo')
df_rank['Score'] = (0.40*df_rank['AUC-ROC(OvR)'] +
                    0.35*df_rank['F1-Macro'] +
                    0.25*df_rank['Acurácia'])
df_rank = df_rank.sort_values('Score', ascending=False)

print('🏆 RANKING FINAL:')
print(df_rank.round(4).to_string())

# Heatmap do ranking
heat_cols = ['AUC-ROC(OvR)','F1-Macro','Acurácia','Precisão','Recall']
df_rank[heat_cols].style\
    .background_gradient(cmap='RdYlGn', axis=0)\
    .format('{:.4f}')\
    .set_caption('🏆 Comparação Final — Conjunto de Teste')

"""# Extra material

## A full pipeline with both preparation and prediction
"""

full_pipeline_with_predictor = Pipeline([
    ('preparation', full_pipeline),
    ('random_forest', grid_search.best_estimator_)
])

X_all = wine.drop('target', axis=1)
y_all = wine['target']
full_pipeline_with_predictor.fit(X_all, y_all)

print('Predições em 4 exemplos:')
some = X_all.iloc[:4]
print('  Predições:', full_pipeline_with_predictor.predict(some))
print('  Reais    :', y_all.iloc[:4].values)

"""## Model persistence using joblib"""

import joblib

joblib.dump(full_pipeline_with_predictor, 'modelo_vinho.pkl')
print('✅ Modelo salvo: modelo_vinho.pkl')

modelo_carregado = joblib.load('modelo_vinho.pkl')
preds = modelo_carregado.predict(some)
probas = modelo_carregado.predict_proba(some)

print(f'✅ Modelo carregado e testado!')
for i, (pred, prob) in enumerate(zip(preds, probas), 1):
    cultivar = ['Cultivar A','Cultivar B','Cultivar C'][pred]
    print(f'  Vinho {i}: {cultivar}  (P0={prob[0]:.2f} P1={prob[1]:.2f} P2={prob[2]:.2f})')

"""1. Como a escolha do algoritmo influencia o desempenho final?
Cada algoritmo tem suposições diferentes sobre os dados, o que gera resultados distintos mesmo com os mesmos dados. O Random Forest foi o melhor (0 erros, AUC=1.000) por combinar 100 árvores e capturar interações complexas. O KNN cometeu 1 erro por ser sensível ao valor de K. O Naive Bayes cometeu 2 erros por assumir independência entre features que na prática são correlacionadas. Não existe algoritmo universalmente melhor — a escolha depende da natureza dos dados.

2. Quais métricas são mais adequadas para comparar classificadores?
Para classificação multiclasse, AUC-ROC OvR foi a métrica principal por medir separação entre classes independentemente do threshold. O F1-Macro foi essencial por tratar as 3 classes com peso igual, evitando que a classe majoritária mascare o desempenho nas menores. A acurácia simples foi suficiente aqui por as classes estarem relativamente balanceadas, mas o desvio padrão na cross-validation também importa — o KNN teve ±0.041 contra ±0.029 do Random Forest, indicando menor estabilidade.

3. Como a qualidade dos dados pode impactar os resultados?
Três fatores foram decisivos: o dataset não tinha valores ausentes, o que eliminou distorções; o StandardScaler foi essencial para o KNN, pois sem normalização features com escalas diferentes (magnesium: 70–162 vs. nonflavanoid_phenols: 0.13–0.66) dominariam o cálculo de distância; e o Feature Engineering gerou as features mais importantes — color_score ficou em 4º e polyphenol_index em 7º no ranking do Random Forest, superando diversas features originais.

4. Quando modelos simples são mais vantajosos que complexos?
O Naive Bayes treinou em menos de 1ms e obteve AUC perfeito (1.000) na cross-validation de 10 folds, superando o Random Forest (0.9996) nessa métrica. O Grid Search mostrou que usar 50 árvores foi melhor ou igual a usar 200. O KNN otimizado pelo Randomized Search ficou em último lugar (3 erros), pior que o KNN simples (1 erro) — exemplo claro de overfitting na otimização. Modelos simples são preferíveis quando o dataset é pequeno, as features já são discriminativas, há restrição de tempo, ou o ganho do modelo complexo é marginal.
"""